<?php

$newUrl = $this->url('messageboard',
	array('controller' => 'board',
	      'action'=> 'new')
);

$editUrl = $this->url('messageboard',
	array('controller' => 'board',
	      'action'=> 'edit',
	      'id' => $this->board->getId())
);

$deleteUrl = $this->url('messageboard',
	array('controller' => 'board',
	      'action'=> 'delete',
	      'id' => $this->board->getId())
);


echo '<h2>'.$this->board->getTitle().'</h2>';
echo '<a href="'. $newUrl.'">New Board</a><br/><br/>';
echo '<a href="'. $editUrl.'">Edit Board</a><br/><br/>';
echo '<a href="'. $deleteUrl.'">Delete Board</a><br/><br/>';
echo '<div>';
foreach ($this->board->getMessages() as $msg) {
    $created = $this->dateFormat($msg->getCreated(), IntlDateFormatter::SHORT, IntlDateFormatter::SHORT, "nb_NO");
    echo '<div>';
    echo '<div><b>'.$msg->getTitle().'</b> - by '. $msg->getSender().' on <i>'.$created.'</i></div>';
    echo '<div>'.$msg->getContent().'</div>';
    echo '</div>';
}
echo '</div>';