<?php
$form->setAttribute('action', '')->prepare();

echo $this->form()->openTag($form);

$board = $form->get('board');

echo $this->formRow($board->get('title'));
/*echo $this->formRow($board->get('price'));
echo $this->formCollection($board->get('categories'));

$brand = $board->get('brand');

echo $this->formRow($brand->get('name'));
echo $this->formRow($brand->get('url'));

echo $this->formHidden($form->get('csrf'));*/
echo $this->formElement($form->get('submit'));

echo $this->form()->closeTag();